name: Deploy Backend

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: SSH key setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H your_ec2_ip_address >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@18.199.92.253 << EOF
            cd /home/ubuntu/ht-backend
            git pull
            npm install
            pm2 restart all
          EOF
